# Generated by Django 5.0.4 on 2024-04-20 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_roll_no', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=30, null=True)),
                ('student_room_no', models.CharField(max_length=10, null=True)),
                ('student_hostel_status', models.BooleanField(default=True)),
                ('student_hostel_out_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Login',
            fields=[
                ('student_roll_no', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('remember_me', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('room_light_status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.student')),
            ],
        ),
    ]
